<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>Library</OutputType>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="Features\Identity\RefreshToken\RefreshTokenCommandHandler.cs" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.2.0" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="MediatR" Version="14.2.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Shop.Domain\Shop.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Features\Identity\Logout\" />
	  <Folder Include="Features\Identity\Shared\Exceptions\" />
	  <Folder Include="Features\Identity\Shared\Models\" />
	  <Folder Include="Features\Identity\Shared\Abstractions\" />
	</ItemGroup>

</Project>
