<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Core\**" />
    <Compile Remove="Specifications\**" />
    <EmbeddedResource Remove="Core\**" />
    <EmbeddedResource Remove="Specifications\**" />
    <None Remove="Core\**" />
    <None Remove="Specifications\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="8.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Events\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Common\" />
    <Folder Include="ValueObjects\" />
  </ItemGroup>

</Project>
